import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import axios from "../libs/axios";
import React, { useEffect } from 'react';

import { useHandleLogout } from '../components/shared/function/Auth/AuthLisnter'

const handleLogout = useHandleLogout()


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    axios.get("/api/books").then((res) => {
    const data = res.data;
    console.log(data);
   });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <h1>Welcome to Mypage</h1>
          <div className={styles.thirteen}>
            <h1>❤️</h1>
          </div>
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <span
              className={'block px-4 py-2 text-sm text-gray-700 cursor-pointer'}
              onClick={handleLogout}
            >
            ログアウト
            </span>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Link
              className=" text-blue-400 text-xs text-center"
              href={{
                pathname: '/login',
                query: null
              }}
            >
            Login
            </Link>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Link
              className=" text-blue-400 text-xs text-center"
              href={{
                pathname: '/register',
                query: null
              }}
            >
            Register
            </Link>
          </div>
        </div>
      </main>

    </>
  )
}
