#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd api/laravel-api && npm run prettier -- app/* --write && npm run prettier -- config/* --write && npm run prettier -- database/* --write && npm run prettier -- lang/* --write && npm run prettier -- resources/* --write && npm run prettier -- routes/* --write && npm run prettier -- tests/* --write
